#
# MS Security Checks
#
pool:
  vmImage: windows-latest

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
      - release/*

steps:
  - task: CredScan@3
    inputs:
      outputFormat: sarif
      debugMode: false

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - task: PublishSecurityAnalysisLogs@3
    inputs:
      ArtifactName: 'CodeAnalysisLogs'
      ArtifactType: 'Container'
