#
# App CI
#
name: Greenlight CI
pool:
  vmImage: windows-latest

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
      - release/*

steps:
  # Install Tooling
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: '14.x'

  # Install Dependencies
  - task: Bash@3
    displayName: Install Dependencies
    inputs:
      targetType: 'inline'
      script: yarn install
    env:
      CI: true

  # Verify Packages
  - task: Bash@3
    displayName: Verify Packages
    inputs:
      targetType: 'inline'
      script: yarn ci
    env:
      CI: true

  # Archive API (Prepare Deploy Zip)
  - task: Bash@3
    displayName: Verify Packages
    inputs:
      targetType: 'inline'
      script: yarn archive:api
    env:
      CI: true

  # API Deploy (Integ)
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      ConnectedServiceName: 'Resilience(28d5908e-8e17-4a1d-a099-0e45af739a9c)'
      WebAppName: 'greenlight-api-integ'
      packageForLinux: '$(System.DefaultWorkingDirectory)/packages/api/deploy.zip'

  # API Deploy (Prod)
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      ConnectedServiceName: 'Resilience(28d5908e-8e17-4a1d-a099-0e45af739a9c)'
      WebAppName: 'greenlight-api-integ'
      packageForLinux: '$(System.DefaultWorkingDirectory)/packages/api/deploy.zip'

  # - task: Bash@3
  #   displayName: Prepare Webapp Deployment
  #   inputs:
  #     targetType: 'inline'
  #     script: yarn predeploy:webapp
  #   env:
  #     CI: true

  # - task: AzureRmWebAppDeployment@4
  #   inputs:
  #     ConnectionType: 'PublishProfile'
  #     PublishProfilePath: '$(System.DefaultWorkingDirectory)/webapp.pubxml'
  #     PublishProfilePassword: '$(webapp.publish_password)'
  #     packageForLinux: '$(System.DefaultWorkingDirectory)/packages/webapp/deploy.zip'
