name: Project Resolve CI
pool:
  vmImage: windows-latest

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
      - release/*

stages:
  # Giving a common root to starting tasks allows them to parallelize
  - stage: Kickoff
    jobs:
      - job: KickoffJob
        steps:
          - task: Bash@3
            displayName: Announce Kickoff
            inputs:
              targetType: 'inline'
              script: echo "Kickoff!"

  - stage: Compliance
    dependsOn:
      - Kickoff
    jobs:
      - job: ComplianceJob
        steps:
          - task: CredScan@3
            inputs:
              outputFormat: sarif
              debugMode: false

          - task: ComponentGovernanceComponentDetection@0
            inputs:
              scanType: 'Register'
              verbosity: 'Verbose'
              alertWarningLevel: 'High'

          - task: PublishSecurityAnalysisLogs@3
            inputs:
              ArtifactName: 'CodeAnalysisLogs'
              ArtifactType: 'Container'

  - stage: Verification
    dependsOn:
      - Kickoff
    jobs:
      - job: VerificationJob
        steps:
          # Install Tooling
          - task: NodeTool@0
            displayName: Install Node
            inputs:
              versionSpec: '14.x'

          # Install Dependencies
          - task: Bash@3
            displayName: Install Dependencies
            inputs:
              targetType: 'inline'
              script: yarn install
            env:
              CI: true
          # Verify Packages
          - task: Bash@3
            displayName: Verify Packages
            inputs:
              targetType: 'inline'
              script: yarn ci
            env:
              CI: true

  - stage: ApiDeploymentInteg
    displayName: Deploy API (Integ)
    dependsOn:
      - Compliance
      - Verification
    #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - job: ApiDeploymentJob
        steps:
          - task: Bash@3
            displayName: Archive API
            inputs:
              targetType: 'inline'
              script: yarn build:schema && yarn build:api && yarn archive:api
            env:
              CI: true

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy API (Integ)
            inputs:
              ConnectionType: 'AzureRM'
              appType: 'webAppLinux'
              ConnectedServiceName: 'Resilience - Greenlight'
              WebAppName: 'greenlight-api-integ'
              packageForLinux: '$(System.DefaultWorkingDirectory)/packages/api/deploy.zip'

  - stage: ApiDeploymentProd
    displayName: Deploy API (Prod)
    dependsOn:
      - Compliance
      - Verification
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
    jobs:
      - job: ApiDeploymentJob
        steps:
          - task: Bash@3
            displayName: Archive API
            inputs:
              targetType: 'inline'
              script: yarn build:schema && yarn build:api && yarn archive:api
            env:
              CI: true

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy API (Prod)
            condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
            inputs:
              ConnectionType: 'AzureRM'
              appType: 'webAppLinux'
              ConnectedServiceName: 'Resilience - Greenlight'
              WebAppName: 'greenlight-api-integ'
              packageForLinux: '$(System.DefaultWorkingDirectory)/packages/api/deploy.zip'

  - stage: ClientDeploymentInteg
    displayName: Deploy Webapp (Integ)
    #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    dependsOn:
      - Compliance
      - Verification
    jobs:
      - job: ClientDeploymentJob
        steps:
          - task: Bash@3
            displayName: Build Webapp (Integ)
            inputs:
              targetType: 'inline'
              script: yarn build:schema && yarn build:webapp:integ
            env:
              CI: true

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Webapp (Integ)
            inputs:
              ConnectionType: 'AzureRM'
              appType: 'webAppLinux'
              ConnectedServiceName: 'Resilience - Greenlight'
              WebAppName: 'greenlight-app-integ'
              packageForLinux: '$(System.DefaultWorkingDirectory)/packages/webapp/deploy.zip'

  - stage: ClientDeploymentProd
    displayName: Deploy Webapp (Prod)
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))
    dependsOn:
      - Compliance
      - Verification
    jobs:
      - job: ClientDeploymentJob
        steps:
          - task: Bash@3
            displayName: Build Webapp (Prod)
            inputs:
              targetType: 'inline'
              script: yarn build:schema && yarn build:webapp:prod
            env:
              CI: true

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy Webapp (Prod)
            inputs:
              ConnectionType: 'AzureRM'
              appType: 'webAppLinux'
              ConnectedServiceName: 'Resilience - Greenlight'
              WebAppName: 'greenlight-app'
              packageForLinux: '$(System.DefaultWorkingDirectory)/packages/webapp/deploy.zip'
