#
# App CI
#
pool:
  vmImage: windows-latest

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main
      - release/*

steps:
  # Install Tooling
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: '14.x'

  # Install Dependencies
  - task: Bash@3
    displayName: Install Dependencies
    inputs:
      targetType: 'inline'
      script: yarn install
    env:
      CI: true

  # Verify Packages
  - task: Bash@3
    displayName: Verify Packages
    inputs:
      targetType: 'inline'
      script: yarn ci
    env:
      CI: true
