plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  '@fluentui/foundation-legacy@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/react-focus@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/react-hooks@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/style-utilities@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/react@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/theme@*':
    peerDependencies:
      '@types/react': "*"
  '@fluentui/utilities@*':
    peerDependencies:
      '@types/react': "*"
  'redux-thunk@*': 
    peerDependencies:
      'redux': '*'
  'redux-persist@*':
    peerDependencies:
      '@types/react': '*'
  'next@*':
    peerDependencies:
      '@types/react-dom': '*'