enableInlineHunks: true

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/foundation-legacy@*":
    peerDependencies:
      "@types/react": "*"
  "@fluentui/react-focus@*":
    peerDependencies:
      "@types/react": "*"
  "@fluentui/react-hooks@*":
    peerDependencies:
      "@types/react": "*"
  "@fluentui/react@*":
    peerDependencies:
      "@types/react": "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@fluentui/theme@*":
    peerDependencies:
      "@types/react": "*"
  "@fluentui/utilities@*":
    peerDependencies:
      "@types/react": "*"
  apollo-server-fastify@*:
    dependencies:
      fast-json-stringify: "*"
  babel-plugin-transform-typescript-metadata@*:
    peerDependencies:
      "@babel/core": "*"
  next@*:
    peerDependencies:
      "@types/react-dom": "*"
  redux-persist@*:
    peerDependencies:
      "@types/react": "*"
      react: "*"
  redux-thunk@*:
    peerDependencies:
      redux: "*"
  webdriverio@*:
    peerDependencies:
      debug: "*"
  devtools@*:
    peerDependencies:
      debug: "*"
  "@wdio/cli@*":
    peerDependencies:
      debug: "*"
  "@wdio/devtools-service@*":
    peerDependencies:
      debug: "*"
  "@wdio/runner@*":
    peerDependencies:
      debug: "*"
  "@wdio/sauce-service@*":
    peerDependencies:
      debug: "*"
  "@wdio/local-runner@*":
    peerDependencies:
      debug: "*"
  applicationinsights@*:
    dependencies:
      "@opentelemetry/semantic-conventions": "^0.24.0"
      "@opentelemetry/core": "^0.23.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
