#
# compose file for local env -
#   spins up a database instance for the app to use
#
version: '3'
services:
  mongodb:
    image: mongo:4.0.27
    ports:
      - '27017:27017'
    volumes:
      - dbvolume:/data
    environment: { AUTH: 'no' }

volumes:
  dbvolume: {}
