version: '3'
services:
  workspace:
    build:
      context: .
      dockerfile: 'Dockerfile'
    volumes:
      - .:/ws:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - 'NODE_CONFIG_ENV=codespaces'
    links:
      - mongodb

  mongodb:
    image: mongo:3.6.16
    ports:
      - '27017:27017'
    volumes:
      - dbvolume:/data
    environment: { AUTH: 'no' }
volumes:
  dbvolume: {}
